export const MAP_IMAGES = [
	{ name: "現在", file: "Map1a_PALEOMAP_PaleoAtlas_000.jpg" },
	{ name: "最終氷期極大期", file: "Map2a_Last_Glacial_Maximum_001.jpg" },
	{ name: "鮮新世", file: "Map3a_Pliocene_004.jpg" },
	{ name: "メッシニアン期", file: "Map4a_Messinian_Event_006.jpg" },
	{ name: "中新世後期", file: "Map5a_Late_Miocene_010.jpg" },
	{ name: "中新世中期", file: "Map6a_Middle_Miocene_015.jpg" },
	{ name: "中新世前期", file: "Map7a_Early_Miocene_020.jpg" },
	{ name: "漸新世後期", file: "Map8a_Late_Oligocene_025.jpg" },
	{ name: "漸新世前期", file: "Map9a_Early_Oligocene_030.jpg" },
	{ name: "始新世後期", file: "Map10a_Late_Eocene_035.jpg" },
	{ name: "始新世中期", file: "Map11a_MIddle_Eocene_040.jpg" },
	{ name: "始新世前期", file: "Map12a_early_Middle_Eocene_045.jpg" },
	{ name: "始新世最前期", file: "Map13a_Early_Eocene_050.jpg" },
	{ name: "PETM", file: "Map14a_PETM_055.jpg" },
	{ name: "暁新世", file: "Map15a_Paleocene_060.jpg" },
]; 